config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'ramen#index'
  resources :ramen do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    member do
      get :likes
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :ramen
	belongs_to :user
	validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
 	belongs_to :ramen

	validates :ramen_id, uniqueness: { scope: :user_id }
end

app/models/ramen.rb
class Ramen < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_one_attached :image
	def self.search(search)
    if search != ""
      Ramen.where('store_name LIKE(?)', "%#{search}%")
    else
      Ramen.all
    end
  end
	extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :star
	validates :ramen_name,:image,:store_name,:star_id, presence: true
	validates :star_id, numericality: { other_than: 1 , message: "を入力してください"} 
end

app/models/star.rb
class Star < ActiveHash::Base
	self.data = [
		{ id: 1, name: '--' },
		{ id: 2, name: '⭐️' },
		{ id: 3, name: '⭐️⭐️' },
		{ id: 4, name: '⭐️⭐️⭐️' },
		{ id: 5, name: '⭐️⭐️⭐️⭐️' },
		{ id: 6, name: '⭐️⭐️⭐️⭐️⭐️' },
	]
	include ActiveHash::Associations
  has_many :ramen
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ramens, class_name: 'Ramen'
  has_many :likes
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  def liked_by?(ramen_id)
    likes.where(ramen_id: ramen_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    comment = Comment.create(comment_params)
		redirect_to "/ramen/#{comment.ramen_id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, ramen_id: params[:raman_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :ramen_params
 def create
   Like.create(user_id: current_user.id, ramen_id: params[:id])
 end
 
 def destroy
   Like.find_by(user_id: current_user.id, ramen_id: params[:id]).destroy
  end
 
 private
 
 def ramen_params
   @ramen = Ramen.find(params[:id])
 end
end

app/controllers/ramen_controller.rb
class RamenController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :search]
	before_action :set_ramen, only: [:show, :edit, :update,:destroy]
	before_action :move_to_edit, only: [:edit,:update]

	def index
		@ramen = Ramen.all.order("created_at DESC")
	end
	def new
		@ramen = Ramen.new
	end
	def create
		@ramen = Ramen.new(ramen_params)
		if @ramen.save
			redirect_to root_path
		else
      render :new
    end
	end
	def show
		@comment = Comment.new
		@comments = @ramen.comments.includes(:user)
	end
	def edit
	end
	def update
		if @ramen.update(ramen_params)
			redirect_to raman_path
		else
			render :edit
		end
	end
	def destroy
		@ramen.destroy
		redirect_to root_path
	end
	def search
		@ramen = Ramen.search(params[:keyword])
	end
	private
	def ramen_params
		params.require(:ramen).permit(:store_name,:ramen_name,:star_id, :image,:text).merge(user_id: current_user.id)
	end
	def set_ramen
		@ramen = Ramen.find(params[:id])
	end
	def move_to_edit
    unless current_user.id == @ramen.user_id
      redirect_to root_path
    end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show]
 def show
	@user = User.find(params[:id])
	likes = Like.where(user_id: @user.id).pluck(:ramen_id)
	@like_ramens = Ramen.find(likes)
 end
 

	private
	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/ramen_helper.rb
module RamenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Re麺bar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
 <% if current_user.liked_by?(ramen.id) %>
   <div class = 'likes'>
     <%= link_to destroy_like_path(ramen), method: :DELETE, remote: true do %> 
       <div class="fa fa-heart unlike-btn"></div> 
     <% end %> 
     <div class= 'likenum'><%= ramen.likes.count %></div>
   </div>
 	<% else %>
	 <div class = 'likes'>
			<%= link_to create_like_path(ramen), method: :POST, remote: true do %> 
				<i class="fa fa-heart like-btn"></i> 
			<% end %> 
			<div class= 'likenum'><%= ramen.likes.count %></div>
		</div>
 <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @ramen.id %>').html("<%= j(render partial: 'likes/like', locals: {ramen: @ramen}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @ramen.id %>').html("<%= j(render partial: 'likes/like', locals: {ramen: @ramen}) %>");

app/views/ramen/_ramen.html.erb
				<li class='list'>
				<%= link_to raman_path(ramen.id) do%>
				<div class='ramen-img-content'>
					<%= image_tag ramen.image, class: 'ramen-image' if ramen.image.attached? %>
				</div>
				<% end %>
				</li>

app/views/ramen/_ramen2.html.erb
<li class='list'>
	<%= link_to raman_path(ramen.id) do%>
		<div class='ramen-img-content'>
			<%= image_tag ramen.image, class: 'ramen-image' if ramen.image.attached? %>
		</div>
	<% end %>
	<div class = 'ramen-info'>
		<div class = 'store'>
				<%= '店名:' + ramen.store_name %>
			<div class="name">
				<%= '商品名:' + ramen.ramen_name %>
			</div>
			<div class="star">
				<%= 'オススメ度:' + ramen.star.name %>
			</div>
		<div id="likes_buttons_<%= ramen.id %>">
			<%= render partial: 'likes/like', locals: {ramen: ramen} %>
		</div>
	</div>
</li>

app/views/ramen/edit.html.erb
<%= form_with model: @ramen, url:raman_path(@ramen.id), local: true do |f| %>
	<div class="ramen-box">
	編集画面<br />
	<%= f.label :image, "ラーメンの写真" %>
	    <%= f.file_field :image, id:"ramen_image" %><br />
		<%= f.text_field :store_name, class:"title", placeholder:"店名" %><br />
		<%= f.text_field :ramen_name, class:"title", placeholder:"商品名" %><br />
		<%= f.text_area :text, class:"text", placeholder:"テキスト" %><br />
		オススメ度<br />
		<%= f.collection_select(:star_id, Star.all, :id, :name, {}, {class:"star-select"}) %><br />
		<%= f.submit "編集する" ,class:"btn2" %><br />
		<%= link_to :back do%>
		<div class ='topbtn'>戻る</div>
		<%end%>
	</div>
<% end %>

app/views/ramen/index.html.erb
<%# <div class = 'main-header'> %>
			<% unless user_signed_in? %>
				<div class='login'>
						<div class="sample">Re麺bar</div>
					<%= link_to new_user_session_path do %>
						<button class="btn">ログイン</button>
					<%end%>
					<%= link_to new_user_registration_path do %>
						<button class="btn1">新規登録</button>
					<%end%>
				</div>
			<% else %>
				<div class='logout'>
					<div class="sample">Re麺bar	</div>

					<%= link_to  current_user.nickname + 'さん', user_path(current_user.id), class: "topbtn1"%>
					<%= link_to destroy_user_session_path, method: :delete do %>
						<button class="btn">ログアウト</button>
					<%end%>
					<%= link_to new_raman_path do %>
						<button class="btn1">投稿する</button>
					<%end%>
				</div>
			<% end %>
<%# </div> %>
<div class = 'toppege'>
		<div class='main'>
			<%= image_tag "2-1.jpg", class:"noren" %>
		</div> 

		<div class="loading-icon">
					<%= image_tag "なると.jpeg", class:"naruto-icon" %>
			</div>
	<div class= 'main-contents'>			
			<div class='content'>投稿一覧</div>
			<div class ='search'>
				<%= form_with(url: search_ramen_path, local: true, method: :get, class: "search-form") do |form| %>
					<%= form.text_field :keyword, placeholder: "店名を検索する", class: "search-input" %>
					<%= form.submit "検索", class: "search-btn" %>
				<% end %>
			</div>
			<ul class='ramen-contents'>
				<% @ramen.each do |ramen| %>
				<li class='list'>
					<%= link_to raman_path(ramen.id) do%>
						<div class='ramen-img-content'>
							<%= image_tag ramen.image, class: 'ramen-image' if ramen.image.attached? %>
						</div>
					<% end %>
					<div class = 'ramen-info'>
						<div class = 'store'>
						<%= '店名:' + ramen.store_name %>
						<div class="name">
							<%= '商品名:' + ramen.ramen_name %>
						</div>
						<div class="star">
							<%= 'オススメ度:' + ramen.star.name %>
						</div>
						<div id="likes_buttons_<%= ramen.id %>">
							<%= render partial: 'likes/like', locals: {ramen: ramen} %>
						</div>
					</div>
				</li>
				<% end %>
			</ul>
	</div>
	<footer>
		<div class="copyright">
			<p>&copy 2020 - Organisation</p>
		</div>
		<div class="social">
			<a href="#" class="support">Contact </a>
			<a href="#" class="face">f</a>
			<a href="#" class="tweet">t</a>
			<a href="#" class="linked">in</a>
		</div>
	</footer>

app/views/ramen/new.html.erb
<%= form_with model: @ramen, url:ramen_path, local: true do |f| %>
	<div class="ramen-box">
		<%= render 'shared/error_messages', model: @ramen %>
	新規投稿<br />
	<%= f.label :image, "ラーメンの写真" %>
	    <%= f.file_field :image, id:"ramen_image" %><br />
		<%= f.text_field :store_name, class:"title", placeholder:"店名" %><br />
		<%= f.text_field :ramen_name, class:"title", placeholder:"商品名" %><br />
		<%= f.text_area :text, class:"text", placeholder:"テキスト" %><br />
		オススメ度<br />
		<%= f.collection_select(:star_id, Star.all, :id, :name, {}, {class:"star-select"}) %><br />
		<%= f.submit "投稿する" ,class:"btn2" %><br>
<% end %>
		<%= link_to :back do%>
		<div class ='topbtn'>戻る</div>
		<%end%>
	</div>

app/views/ramen/search.html.erb
  <%= link_to root_path do%>
    <div class= 'sample1'>Re麺bar</div>
  <%end%>
<div class= 'searchpage'>
	<div class ='search'>
    <%= form_with(url: search_ramen_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "店名を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    <div class="contents-row">
      <% @ramen.each do |ramen| %>
        <%= render partial: "ramen2", locals: { ramen: ramen } %>
      <% end %>
    </div>
  </div>
</div>

app/views/ramen/show.html.erb
	<div class = 'showmain2'>
		<%=link_to @ramen.user.nickname + 'さんの投稿', user_path(@ramen.user_id),class: 'showuser' %>
				<div class='showramen-img'>
					<%= image_tag @ramen.image, class: 'showramen-image'  %>
				</div>
				<div class = 'showramen-info'>
					<div class = 'store'>
						<%= '店名:' + @ramen.store_name %>
					<div class="showname">
        		<%= '商品名:' + @ramen.ramen_name %>
      		</div>
					<div class="showstar">
        		<%= 'オススメ度:' + @ramen.star.name %>
      		</div>
				</div>

	</div>
					<%if @ramen.text!= '' %>
						<div class="showtext">
        			<%= '感想:' + @ramen.text %>
      			</div>
					<%end%>
	<div class = 'showmain2'>
						<div id= 'likes_buttons_<%= @ramen.id %>'>
							<%= render partial: 'likes/like', locals: {ramen: @ramen} %>
						</div>
				<% if user_signed_in? && current_user.id == @ramen.user_id %>
					<ul class="showlist">
						<li>
							<%= link_to edit_raman_path(@ramen.id), method: :get do %>
							<button class="btn4">編集</button>
							<%end%>
						</li>
						<li>
							<%= link_to raman_path(@ramen.id), method: :delete do %>
							<button class="btn4">削除</button>
							<%end%>
						</li>
				<% end %>
					<%= link_to root_path do%>
							<button class="btn4">ホームへ戻る</button>
					<%end%>
				<div class="commentar">
						<% if user_signed_in? %>
					<%= form_with(model: [@ramen, @comment], local: true) do |form| %>
						<%= form.text_area :text, placeholder: "コメント", rows: "2" %><br>
				</div>
						<div class = 'btn6'>
							<%= form.submit "送信" %>
						</div>
					<% end %>
				<% end %>
						<div class="comments">
							<div class='comment'>＜コメント一覧＞</div>
							<% @comments.each do |comment| %>
								<p>
									<strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
									<%= comment.text %>
								</p>
							<% end %>
						</div>
					</ul>
			</div>
	</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class = 'toppege'>
		<%= link_to root_path do%>
		  <div class= 'sample2'>Re麺bar</div>
		<%end%>
	<div class='content'>
			<%= @user.nickname + 'さんの投稿一覧' %><br>
	</div>
				<ul class='ramen-contents'>
					<%= render partial: 'ramen/ramen', collection: @user.ramens%>
				</ul>
	<div class='content'>
			<%= @user.nickname + 'さんがいいねした投稿' %>
	</div>
			<ul class='ramen-contents'>
				<%= render partial: "ramen/ramen", collection: @like_ramens %>
			</ul>
</div>